### ISSUE TITLE
Min Api version?

### ISSUE THREAD

**Issue by webserveis** [RamiJ3mli/PercentageChartView#13]

**Comment by webserveis** [comment]
I recive "Error: Default interface methods are only supported starting with Android N (--min-api 24): int com.ramijemli.percentagechartview.callback.AdaptiveColorProvider.provideBackgroundBarColor(float)
"

**Comment by RamiJ3mli** [comment]
Default interface methods is a Java 8 feature. So, you should add this to your app module's build.gradle file.
```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
I had to use it to make developers override only the methods they need. Please check and let me know if this works out for you.
