### ISSUE TITLE
Percentage is Zero if 100 is passed.

### ISSUE THREAD

**Issue by JudeOchalifu** [RamiJ3mli/PercentageChartView#3]
Hi.
When calling `chart.setPercentage(100, true)` the final percentage displayed is 0%.
This is not the case when a number <= 99 is used

Is this a known issue, and how do I resolve it?

Best regards

**Comment by RamiJ3mli** [comment]
Hi @JudeOchalifu,
Thank you for pointing it out. 
v0.1.3 was released. Please update your dependency 
```      
    implementation 'com.ramijemli.percentagechartview:percentagechartview:0.1.3' 
```

**Comment by JudeOchalifu** [comment]
Okay.Thanks
