### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by Binary-Finery** [RamiJ3mli/PercentageChartView#9]
got the following errors when trying to run app

com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\User.User-PC\.gradle\caches\transforms-1\files-1.1\percentagechartview-0.3.0.aar\ae6eea35bd6346114908fe1dffe621e2\jars\classes.jar |  
-- | --
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing. |  
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException: Error: Invoke-customs are only supported starting with Android O (--min-api 26) |

**Comment by RamiJ3mli** [comment]
The library is using Java 8 features, so you should add this to your app module's build.gradle file
```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

Please check and let me know if this works out for you
